localizacion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from localizacion.views import Tablero, BusquedaProvincias, BusquedaDistritos,\
    seleccion_distrito, seleccion_prov_consejero, seleccion_provincia,\
    seleccion_region

urlpatterns = [
    url(r'^tablero/$',login_required(Tablero.as_view()), name="tablero"),
    url(r'^busquedaProvincias/$',login_required(BusquedaProvincias.as_view()), name="busquedaProvincias"),
    url(r'^busquedaDistritos/$',login_required(BusquedaDistritos.as_view()), name="busquedaDistritos"),
    url(r'^seleccion_distrito/$',login_required(seleccion_distrito), name="seleccion_distrito"),
    url(r'^seleccion_prov_consejero/$',login_required(seleccion_prov_consejero), name="seleccion_prov_consejero"),
    url(r'^seleccion_provincia/$',login_required(seleccion_provincia), name="seleccion_provincia"),
    url(r'^seleccion_region/$',login_required(seleccion_region), name="seleccion_region"),
]

volpox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'volpox.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('seguridad.urls', namespace='seguridad')),
    url(r'^localizacion/', include('localizacion.urls', namespace='localizacion')),
    url(r'^regional/', include('regional.urls', namespace='regional')),
    url(r'^nacional/', include('nacional.urls', namespace='nacional')),
]

localizacion/models.py
# -*- encoding: utf-8 -*-
from django.db import models

class Region(models.Model):
    nombre = models.CharField(max_length=80)
   
    def __str__(self):
        return self.nombre    

class Provincia(models.Model):
    nombre = models.CharField(max_length=80)
    region = models.ForeignKey(Region)
    
    def __str__(self):
        return self.nombre    

class Distrito(models.Model):
    nombre = models.CharField(max_length=80)
    provincia = models.ForeignKey(Provincia)
    capital_provincia = models.BooleanField(default=None)

    def __str__(self):
        return self.nombre    

class CentroVotacion(models.Model):
    nombre = models.CharField(max_length=50)
    distrito = models.ForeignKey(Distrito)

    def __str__(self):
        return "%s - %s" % (self.nombre, self.distrito)
    
class Partido(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

localizacion/forms.py
from django import forms

localizacion/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.core import serializers
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from localizacion.models import Provincia, Distrito, Region

class Tablero(TemplateView):
    template_name = "tablero_actas.html"        

class BusquedaProvincias(TemplateView):

    def get(self, request, *args, **kwargs):
        region = request.GET['region']
        provincias = Provincia.objects.filter(region=region)
        if provincias:
            data = serializers.serialize('json', provincias, fields= ('pk','nombre'))
        else:
            data = []
        return HttpResponse(data, content_type='application/json')

class BusquedaDistritos(TemplateView):

    def get(self, request, *args, **kwargs):
        provincia = request.GET['provincia']
        distritos = Distrito.objects.filter(provincia=provincia)
        if distritos:
            data = serializers.serialize('json', distritos, fields= ('id','nombre'))
        else:
            data = []
        return HttpResponse(data, content_type='application/json')

def seleccion_distrito(request):
    regiones = Region.objects.order_by('nombre')
    if request.method == 'POST':
        distrito = request.POST['distritos']
        return HttpResponseRedirect(reverse('regional:reporte_distrital', args=[distrito]))
    context = {'regiones':regiones}
    return render(request, 'seleccion_distrito.html', context)

def seleccion_prov_consejero(request):
    regiones = Region.objects.order_by('nombre')
    if request.method == 'POST':
        provincia = request.POST['provincias']
        return HttpResponseRedirect(reverse('regional:reporte_consejero_regional', args=[provincia]))
    context = {'regiones':regiones}
    return render(request, 'seleccion_consejero_prov.html', context)

def seleccion_provincia(request):
    regiones = Region.objects.order_by('nombre')
    if request.method == 'POST':
        provincia = request.POST['provincias']
        return HttpResponseRedirect(reverse('regional:reporte_provincial', args=[provincia]))
    context = {'regiones':regiones}
    return render(request, 'seleccion_provincia.html', context)

def seleccion_region(request):
    regiones = Region.objects.order_by('nombre')
    if request.method == 'POST':
        region = request.POST['regiones']
        return HttpResponseRedirect(reverse('nacional:reporte_congresal', args=[region]))
    context = {'regiones':regiones}
    return render(request, 'seleccion_region.html', context)

localizacion/templates/base_localizacion.html
{% extends "base.html" %}
{% block menu %}
<div class="navbar-default sidebar" role="navigation">
   	<div class="sidebar-nav navbar-collapse">
		<ul class="nav" id="side-menu">
			<li>
		        <a href="#"><i class="fa fa-wrench fa-lg"></i> Configuración<span class="fa arrow"></span></a>
		        <ul class="nav nav-second-level">
		            
		        </ul>	                
		    </li>			    
		    <li>
		        <a href="#"><i class="glyphicon glyphicon-sort"></i> Operaciones<span class="fa arrow"></span></a>
		        <ul class="nav nav-second-level">
					
				</ul>	                    
		    </li>
		    <li>
		    	<a href="#"><i class="glyphicon glyphicon-stats"></i> Reportes<span class="fa arrow"></span></a>
			    <ul class="nav nav-second-level">			    	
				</ul>
		    </li>
    	</ul>	               
	</div>                
</div>

{% endblock menu %}

localizacion/templates/seleccion_consejero_prov.html
{% extends "base_localizacion.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">CONSEJERO REGIONAL</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    SELECCIONE LA REGIÓN Y PROVINCIA
			</div>
			<div class="panel-body">
				<form role="form" action="{% url 'localizacion:seleccion_prov_consejero' %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<label for="regiones">Region: </label>
						<select id="regiones" name="regiones" class="form-control">
							<option>Elige una región</option>
							{% for region in regiones %}
								<option value="{{ region.id }}">{{ region.nombre }}</option>
							{% endfor %}}
						</select>
					</div>
					<div class="form-group">
						<label for="regiones">Provincia: </label>							 
						<select id="provincias" name="provincias" class="form-control">
							<option>Elige una provincia</option>
						</select>
					</div>			
					<input class="btn" type="submit" value="Siguiente">								
				</form>
			</div>					
		</div>
	</div>
</div>
{% endblock cuerpo %}

{% block js %}
	<script>
	$('#regiones').on('change',busquedaProvincias);
	function busquedaProvincias(){
		var region = $('#regiones').val();
		$("#provincias").empty();
		$("#provincias").append("<option>Elige una provincia</option>");
		$.ajax({
			data : {'region': region},
			url : '{% url 'localizacion:busquedaProvincias' %}',
			type : 'get',
			success : function(data){
				$.each(data, function(i,item){
            		$("#provincias").append("<option value=\""+item.pk+"\">"+item.fields.nombre+"</option>");
        		});
			}
		});
	}

	$('#provincias').on('change',busquedaDistritos);
	function busquedaDistritos(){
		var provincia = $('#provincias').val();
		$("#distritos").empty();
		$("#distritos").append("<option>Elige un distrito</option>");
		$.ajax({
			data : {'provincia': provincia},
			url : '{% url 'localizacion:busquedaDistritos' %}',
			type : 'get',
			success : function(data){
				$.each(data, function(i,item){
            		$("#distritos").append("<option value=\""+item.pk+"\">"+item.fields.nombre+"</option>");
        		});
			}
		});
	}
	
	</script>
{% endblock js %}

localizacion/templates/seleccion_distrito.html
{% extends "base_localizacion.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">MUNICIPALIDAD DISTRITAL</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    SELECCIONE LA REGIÓN, PROVINCIA Y DISTRITO
			</div>
			<div class="panel-body">
				<form role="form" action="{% url 'localizacion:seleccion_distrito' %}" method="post">				
					{% csrf_token %}
					<div class="form-group">
						<label for="regiones">Region: </label> 
						<select id="regiones" name="regiones" class="form-control">
							<option>Elige una región</option>
							{% for region in regiones %}
								<option value="{{ region.id }}">{{ region.nombre }}</option>
							{% endfor %}}
						</select>
					</div>
					<div class="form-group">
						<label for="regiones">Provincia: </label>
						<select id="provincias" name="provincias" class="form-control">
							<option>Elige una provincia</option>
						</select>
					</div>
					<div class="form-group">
						<label for="regiones">Distrito: </label>
						<select id="distritos" name="distritos" class="form-control">
							<option>Elige un distrito</option>
						</select>
					</div>			
					<div class="span4">
						<input class="btn" type="submit" value="Siguiente">
					</div>			
				</form>
			</div>					
		</div>
	</div>
</div>
{% endblock cuerpo %}

{% block js %}
	<script>
	$('#regiones').on('change',busquedaProvincias);
	function busquedaProvincias()
	{
		var region = $('#regiones').val();
		$("#provincias").empty();
		$("#provincias").append("<option>Elige una provincia</option>");
		$.ajax({
			data : {'region': region},
			url : '{% url 'localizacion:busquedaProvincias' %}',
			type : 'get',
			success : function(data){
				$.each(data, function(i,item){
            		$("#provincias").append("<option value=\""+item.pk+"\">"+item.fields.nombre+"</option>");
        		});
			}
		});
	}

	$('#provincias').on('change',busquedaDistritos);
	function busquedaDistritos(){
		var provincia = $('#provincias').val();
		$("#distritos").empty();
		$("#distritos").append("<option>Elige un distrito</option>");
		$.ajax({
			data : {'provincia': provincia},
			url : '{% url 'localizacion:busquedaDistritos' %}',
			type : 'get',
			success : function(data){
				$.each(data, function(i,item){
            		$("#distritos").append("<option value=\""+item.pk+"\">"+item.fields.nombre+"</option>");
        		});
			}
		});
	}
	
	</script>
{% endblock js %}

localizacion/templates/seleccion_provincia.html
{% extends "base_localizacion.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">MUNICIPALIDAD PROVINCIAL</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    SELECCIONE LA REGIÓN Y PROVINCIA
			</div>
			<div class="panel-body">
				<form role="form" action="{% url 'localizacion:seleccion_provincia' %}" method="post">	
					{% csrf_token %}
					<div class="form-group">
						<label for="regiones">Region: </label>
						<select id="regiones" name="regiones" class="form-control">
							<option>Elige una región</option>
							{% for region in regiones %}
							<option value="{{ region.id }}">{{ region.nombre }}</option>
							{% endfor %}}
						</select>
					</div>
					<div class="form-group">
						<div class="span3">
							<label for="provincias">Provincia: </label> 
							<select id="provincias" name="provincias" class="form-control">
								<option>Elige una provincia</option>
							</select>
						</div>
					</div>
					<div class="span4">
						<input class="btn" type="submit" value="Siguiente">
					</div>			
				</form>
			</div>					
		</div>
	</div>
</div>
{% endblock cuerpo %}

{% block js %}
<script>
	$('#regiones').on('change',busquedaProvincias);
	function busquedaProvincias(){
		var region = $('#regiones').val();
		$("#provincias").empty();
		$("#provincias").append("<option>Elige una provincia</option>");
		$.ajax({
			data : {'region': region},
			url : '{% url 'localizacion:busquedaProvincias' %}',
			type : 'get',
			success : function(data){
				$.each(data, function(i,item){
            		$("#provincias").append("<option value=\""+item.pk+"\">"+item.fields.nombre+"</option>");
        		});
			}
		});
	}

	$('#provincias').on('change',busquedaDistritos);
	function busquedaDistritos(){
		var provincia = $('#provincias').val();
		$("#distritos").empty();
		$("#distritos").append("<option>Elige un distrito</option>");
		$.ajax({
			data : {'provincia': provincia},
			url : '{% url 'localizacion:busquedaDistritos' %}',
			type : 'get',
			success : function(data){
				$.each(data, function(i,item){
            		$("#distritos").append("<option value=\""+item.pk+"\">"+item.fields.nombre+"</option>");
        		});
			}
		});
	}
	
</script>
{% endblock js %}

localizacion/templates/seleccion_region.html
{% extends "base_localizacion.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">RESULTADOS AL CONGRESO</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    SELECCIONE LA REGION
			</div>
			<div class="panel-body">
				<form role="form" action="{% url 'localizacion:seleccion_region' %}" method="post">
					{% csrf_token %}
					<div class="form-group">
						<label for="mesas">Region: </label>
						<select id="regiones" name="regiones" class="form-control">
							<option>Elige una región</option>
							{% for region in regiones %}
								<option value="{{ region.id }}">{{ region.nombre }}</option>
							{% endfor %}}
						</select>
					</div>
			
					<div class="span4">
						<input class="btn" type="submit" value="Siguiente">
					</div>			
				</form>
			</div>					
		</div>
	</div>
</div>			

{% endblock cuerpo %}
{% block js %}
	<script>
	
	
	</script>
{% endblock js %}

localizacion/templates/tablero_localizacion.html
{% extends "base_localizacion.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tablero</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    <i class="fa fa-bell fa-fw"></i>Panel de Notificaciones.
			</div>
			<div class="panel-body">
				<div class="list-group">
					{% for notificacion in notificaciones %}
						<p class="list-group-item">{{ notificacion }}</p>
					{% endfor %}
				</div>			
			</div>
		</div>
	</div>
</div>
{% endblock cuerpo %}

{% block js %}
<script language="javascript" type="text/javascript">
</script>
{% endblock js %}