nacional/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from nacional.views import MesaPresidencial, Tablero, ProcesarActaPresidencial, \
    ReportePresidente, ActasPresidenciales, MesasNacionales, MesaCongresal, \
    ProcesarActaCongresal, ActasCongresales, ReporteCongresal

urlpatterns = [
    url(r'^tablero/$', login_required(Tablero.as_view()), name="tablero"),
    url(r'^mesa_presidencial/$', login_required(MesaPresidencial.as_view()), name="mesa_presidencial"),
    url(r'^mesa_congresal/$', login_required(MesaCongresal.as_view()), name="mesa_congresal"),
    url(r'^reporte_presidente/$', login_required(ReportePresidente.as_view()), name="reporte_presidente"),
    url(r'^acta_presidencial/(?P<numero>\d+)/$', login_required(ProcesarActaPresidencial.as_view()),
        name="acta_presidencial"),
    url(r'^acta_congresal/(?P<numero>\d+)/$', login_required(ProcesarActaCongresal.as_view()), name="acta_congresal"),
    url(r'^actas_presidenciales/$', login_required(ActasPresidenciales.as_view()), name="actas_presidenciales"),
    url(r'^actas_congresales/$', login_required(ActasCongresales.as_view()), name="actas_congresales"),
    url(r'^mesas_nacionales/$', login_required(MesasNacionales.as_view()), name="mesas_nacionales"),
    url(r'^reporte_congresal/(?P<region>\d+)/$', login_required(ReporteCongresal.as_view()), name="reporte_congresal"),
]

seguridad/urls.py
from django.conf.urls import url
from django.contrib.auth.views import logout
from seguridad.views import Inicio, Login, CambiarPassword, CrearPermiso, CrearVista, ReportePermisos, ReporteVistas, BorrarPermiso, CrearPerfil, ReportePerfiles, CrearPermisoPerfil,ReportePermisosPerfil,CrearPerfilUsuario, BorrarPermisoPerfil, Permisos, PermisoDenegado,\
    ReporteUsuariosPerfil, ReporteUsuarios, ReportePerfilesUsuario, CrearOpcion,\
    AplicacionesProyecto, CrearPermisoOpcion, ReporteOpcionesPerfil,\
    ReporteVistasOpcion, OpcionesAplicacion, ReporteAplicacionesPerfil
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', Login.as_view(), name="login"),
    url(r'^inicio/$',login_required(Inicio.as_view()), name="inicio"),
    url(r'^permisos/$',login_required(Permisos.as_view()), name="permisos"),
    url(r'^permiso_denegado/$', login_required(PermisoDenegado.as_view()), name="permiso_denegado"),
    url(r'^cambiar_password$', login_required(CambiarPassword.as_view()), name="cambiar_password"),
    url(r'^crear_permiso$', login_required(CrearPermiso.as_view()), name="crear_permiso"),
    url(r'^reporte_permisos$', login_required(ReportePermisos.as_view()), name="reporte_permisos"),
    url(r'^reporte_vistas$', login_required(ReporteVistas.as_view()), name="reporte_vistas"),
    url(r'^reporte_perfiles$', login_required(ReportePerfiles.as_view()), name="reporte_perfiles"),
    url(r'^crear_vista$', login_required(CrearVista.as_view()), name="crear_vista"),
    url(r'^crear_perfil$', login_required(CrearPerfil.as_view()), name="crear_perfil"),
    url(r'^aplicaciones_proyecto', login_required(AplicacionesProyecto.as_view()), name="aplicaciones_proyecto"),
    url(r'^crear_opcion/(?P<aplicacion>.+)/$', login_required(CrearOpcion.as_view()), name="crear_opcion"),
    url(r'^opciones_aplicacion/(?P<aplicacion>.+)/(?P<perfil>.+)/$', login_required(OpcionesAplicacion.as_view()), name="opciones_aplicacion"),
    url(r'^salir$', logout, name="salir", kwargs={'next_page': '/'}),
    url(r'^borrar_permiso/(?P<pk>\d+)/$',BorrarPermiso.as_view(), name="borrar_permiso"),
    url(r'^borrar_permiso_perfil/(?P<pk>\d+)/$',BorrarPermisoPerfil.as_view(), name="borrar_permiso_perfil"),
    url(r'^crear_permiso_perfil$', login_required(CrearPermisoPerfil.as_view()), name="crear_permiso_perfil"),
    url(r'^reporte_aplicaciones_perfil/(?P<perfil>\d+)/$', login_required(ReporteAplicacionesPerfil.as_view()), name="reporte_aplicaciones_perfil"),
    url(r'^reporte_opciones_perfil/(?P<perfil>\d+)/(?P<aplicacion>.+)/$', login_required(ReporteOpcionesPerfil.as_view()), name="reporte_opciones_perfil"),
    url(r'^reporte_permisos_perfil/(?P<perfil>\d+)/$', login_required(ReportePermisosPerfil.as_view()), name="reporte_permisos_perfil"),        
    url(r'^crear_perfil_usuario$', login_required(CrearPerfilUsuario.as_view()), name="crear_perfil_usuario"),
    url(r'^reporte_usuarios/$', login_required(ReporteUsuarios.as_view()), name="reporte_usuarios"),  
    url(r'^reporte_usuarios_perfil/(?P<perfil>\d+)/$', login_required(ReporteUsuariosPerfil.as_view()), name="reporte_usuarios_perfil"),
    url(r'^reporte_vistas_opcion/(?P<opcion>\d+)/$', login_required(ReporteVistasOpcion.as_view()), name="reporte_vistas_opcion"),
    url(r'^reporte_perfiles_usuario/(?P<usuario>\d+)/$', login_required(ReportePerfilesUsuario.as_view()), name="reporte_perfiles_usuario"),
    url(r'^crear_permiso_opcion/$', login_required(CrearPermisoOpcion.as_view()), name="crear_permiso_opcion"),        
]

volpox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'volpox.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('seguridad.urls', namespace='seguridad')),
    url(r'^localizacion/', include('localizacion.urls', namespace='localizacion')),
    url(r'^regional/', include('regional.urls', namespace='regional')),
    url(r'^nacional/', include('nacional.urls', namespace='nacional')),
]

seguridad/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import smart_str

class Vista(models.Model):
    nombre = models.CharField(max_length=150)

    class Meta:
        unique_together = (('nombre'),)

    def __str__(self):
        return self.nombre    

class Perfil(models.Model):
    nombre = models.CharField(max_length=150)

    class Meta:
        unique_together = (('nombre'),)

    def __str__(self):
        return self.nombre

class PermisoPerfil(models.Model):
    perfil = models.ForeignKey(Perfil)
    vista = models.ForeignKey(Vista)

    class Meta:
        unique_together = (('perfil', 'vista'),)

class UsuarioPerfil(models.Model):
    usuario = models.ForeignKey(User)
    perfil = models.ForeignKey(Perfil)

    class Meta:
        unique_together = (('usuario', 'perfil'),)
        
class Opcion(models.Model):
    nombre = models.CharField(max_length=150)
    modulo = models.CharField(max_length=100)
    vistas = models.ManyToManyField(Vista)
    
    def __str__(self):
        return smart_str(self.nombre)
    
    class Meta:
        unique_together = (('nombre'),)
    
class OpcionPerfil(models.Model):
    opcion = models.ForeignKey(Opcion)
    perfil = models.ForeignKey(Perfil)

seguridad/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse, reverse_lazy
from django.http.response import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from seguridad.forms import FormularioCambioPassword,FormularioLogin,\
    FormularioPerfiles
from django.views.generic import View
from seguridad.models import Vista, Perfil, PermisoPerfil,UsuarioPerfil,\
    Opcion, OpcionPerfil
from django.views.generic.edit import CreateView, DeleteView
from django.views.generic import ListView
from django.contrib.auth.views import logout
from django.contrib.auth.models import User
import sys, inspect
import volpox.settings

class Permiso():
    
    def revisar_permisos(self, usuario):        
        nombre_clase = self.__class__.__name__
        try:
            perfiles=UsuarioPerfil.objects.filter(usuario=usuario)
            for perfil_usuario in perfiles:
                try:
                    vista=Vista.objects.get(nombre=nombre_clase)
                except Vista.DoesNotExist:
                    vista = Vista()
                    vista.nombre = nombre_clase
                    vista.save()
                opciones = vista.opcion_set.all()
                for opcion in opciones:
                    try:
                        OpcionPerfil.objects.get(opcion=opcion,perfil=perfil_usuario.perfil)
                        return True
                    except:
                        pass
            return False        
        except UsuarioPerfil.DoesNotExist:
            return False
        
    def obtener_opciones(self,usuario):
        perfiles=UsuarioPerfil.objects.filter(usuario=usuario)
        lista_opciones =[]
        for perfil_usuario in perfiles:
            permisos_opciones = OpcionPerfil.objects.filter(perfil=perfil_usuario.perfil)
            for permiso_opcion in permisos_opciones:
                lista_opciones.append(permiso_opcion.opcion.nombre)
        return lista_opciones

class Inicio(View):
    
    def get(self, request, *args, **kwargs):
        
        return render(request,'bienvenida.html')
    
class Login(View):
    
    def get(self, request, *args, **kwargs):
        form = FormularioLogin()
        context = {'form':form}
        return render(request, 'login.html',context)

    def post(self, request, *args, **kwargs):
        form = FormularioLogin(request.POST)
        if form.is_valid():
            r_username = request.POST['usuario']
            r_password = request.POST['password']
            usuario = authenticate(username=r_username, password=r_password)
            login(request, usuario)
            return HttpResponseRedirect(reverse('seguridad:inicio'))                         
        context = {'form':form}
        return render(request, 'login.html', context)       

class CambiarPassword(View):

    def get(self, request, *args, **kwargs):
        form = FormularioCambioPassword(request.user)
        context = {'form':form}
        return render(request, 'cambiar_password.html', context)

    def post(self, request, *args, **kwargs):
        usuario = request.user
        form = FormularioCambioPassword(usuario,request.POST)
        if form.is_valid():
            password_nueva=request.POST['password_nueva']
            usuario.set_password(password_nueva)
            usuario.save()
            logout(request)
            return HttpResponseRedirect(reverse('seguridad:login'))
        context = {'form':form}
        return render(request, 'cambiar_password.html', context)

class Permisos(Permiso, View):

    def dispatch(self, request, *args, **kwargs):
        if self.revisar_permisos(request.user):
            clase = type(self)
            return super(clase, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('seguridad:permiso_denegado'))

    def get(self, request, *args, **kwargs):
        return render(request,'bienvenida_permisos.html')
    
class PermisoDenegado(View):
    def get(self, request, *args, **kwargs):
        return render(request,'permiso_denegado.html')

class CrearPermiso(CreateView):
    model = Permiso
    fields = ['usuario','vista']
    template_name = 'crear_permiso.html'
    success_url = reverse_lazy('seguridad:crear_permiso')

class CrearPermisoPerfil(Permiso, CreateView):
    model = PermisoPerfil
    fields = ['perfil','vista']
    template_name = 'crear_permiso_perfil.html'
    success_url = reverse_lazy('seguridad:crear_permiso_perfil')
    
    def dispatch(self, request, *args, **kwargs):
        if self.revisar_permisos(request.user):
            clase = type(self)
            return super(clase, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('seguridad:permiso_denegado'))

class CrearPerfilUsuario2(CreateView):
    model = UsuarioPerfil
    fields = ['usuario','perfil']
    template_name = 'crear_perfil_usuario.html'
    success_url = reverse_lazy('seguridad:crear_perfil_usuario')
    
class CrearPerfilUsuario(Permiso, View):  
    
    def dispatch(self, request, *args, **kwargs):
        if self.revisar_permisos(request.user):
            clase = type(self)
            return super(clase, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('seguridad:permiso_denegado'))
    
    def get(self, request, *args, **kwargs):
        try:
            usuarios = User.objects.all().order_by('username')            
            perfiles = Perfil.objects.all().order_by('nombre') 
            context={'usuarios':usuarios,'perfiles':perfiles}             
            return render(request, 'crear_perfil_usuario.html',context)
        except:
            return HttpResponseRedirect(reverse('reclamos:busqueda_simulacion_baja_deudas'))        
    
    def post(self, request, *args, **kwargs):
        expediente = request.POST['expediente']  
        return self.exportar_simulacion_deudas_prescritas(request,expediente)

class AplicacionesProyecto(Permiso, View):    
    
    def get(self, request, *args, **kwargs):
        aplicaciones = [ app for app in siad.settings.INSTALLED_APPS if not "django" in app ]
        context={'aplicaciones':aplicaciones}             
        return render(request, 'reporte_aplicaciones.html',context)
    
    def dispatch(self, request, *args, **kwargs):
        if self.revisar_permisos(request.user):
            clase = type(self)
            return super(clase, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('seguridad:permiso_denegado'))
    
class CrearOpcion(Permiso, View):
    
    def dispatch(self, request, *args, **kwargs):
        if self.revisar_permisos(request.user):
            clase = type(self)
            return super(clase, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('seguridad:permiso_denegado'))
    
    def get(self, request, *args, **kwargs):
        aplicacion = self.kwargs['aplicacion']
        lista_clases = []
        for nombre_modulo,instancia_modulo in inspect.getmembers(sys.modules[aplicacion]):
            if nombre_modulo=='views':
                codigo_fuente = inspect.getsource(instancia_modulo)
                codigo_fuente = codigo_fuente.replace(" ", "")
                for miembro in dir(instancia_modulo):
                    obj = getattr(instancia_modulo, miembro)
                    if inspect.isclass(obj):
                        cadena_clase = 'class' + miembro
                        if codigo_fuente.find(cadena_clase)>=0:
                            lista_clases.append(miembro)
        context={'vistas':lista_clases,'aplicacion':aplicacion}
        return render(request, 'reporte_vistas_aplicacion.html',context)
    
    def post(self, request, *args, **kwargs):
        nombre_vista = request.POST['nombre_vista']
        aplicacion = request.POST['aplicacion']
        vistas = request.POST.getlist('vistas')
        try:
            opcion = Opcion.objects.get(nombre=nombre_vista)
        except:
            opcion = Opcion()
            opcion.nombre = nombre_vista
            opcion.modulo= aplicacion
            opcion.save()
        for vista in vistas:
            try:
                vista_obj = Vista.objects.get(nombre=vista)
            except Vista.DoesNotExist:
                vista_obj = Vista()
                vista_obj.nombre = vista
                vista_obj.save()
            opcion.vistas.add(vista_obj)
        return HttpResponseRedirect(reverse('seguridad:aplicaciones_proyecto'))
        
class CrearPerfil(Permiso, CreateView):
    model = Perfil
    fields = ['nombre']
    template_name = 'crear_perfil.html'
    success_url = reverse_lazy('seguridad:crear_perfil')
    
    def dispatch(self, request, *args, **kwargs):
        if self.revisar_permisos(request.user):
            clase = type(self)
            return super(clase, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('seguridad:permiso_denegado'))

class CrearVista(Permiso, CreateView):
    model = Vista
    fields = ['nombre']
    template_name = 'crear_vista.html'
    success_url = reverse_lazy('seguridad:crear_vista')
    
    def dispatch(self, request, *args, **kwargs):
        if self.revisar_permisos(request.user):
            clase = type(self)
            return super(clase, self).dispatch(request, *args, **kwargs)
        else:
            return HttpResponseRedirect(reverse('seguridad:permiso_denegado'))

class BorrarPermiso(DeleteView):
    model = Permiso
    template_name = 'borrar_permiso.html'
    success_url = reverse_lazy('seguridad:reporte_permisos')

class BorrarPermisoPerfil(DeleteView):
    model = PermisoPerfil
    template_name = 'borrar_permiso_perfil.html'
    success_url = reverse_lazy('seguridad:reporte_permisos_perfil')

class ReportePermisos(ListView):
    model = Permiso

seguridad/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="description" content="">
	    <meta name="author" content="">
		<title>VOLPOX - Software de Control de Actas Electorales</title>
	    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">	    
	    <link href="{% static "css/jquery-ui.css"  %}" rel="stylesheet" type="text/css" />
	    <link href="{% static "css/sticky-footer-navbar.css"  %}" rel="stylesheet" type="text/css" >
	    <link href="{% static "css/jquery.appendGrid-1.6.0.css"  %}" rel="stylesheet" type="text/css" />
	    <link href="{% static "css/jquery.timeentry.css"  %}" rel="stylesheet" type="text/css" />	
	    <link href="{% static "css/font-awesome.min.css"  %}" rel="stylesheet" type="text/css" />
	    <link href="{% static "css/sb-admin-2.css"  %}" rel="stylesheet" type="text/css" />
	    <link href="{% static "css/metisMenu.min.css"  %}" rel="stylesheet" type="text/css" />
	    <link href="{% static "css/jquery.dataTables.min.css"  %}" rel="stylesheet" type="text/css" />
	    <link href="{% static "css/wickedpicker.css"  %}" rel="stylesheet" type="text/css" />    
	    <script src="{% static "js/jquery.js" %}"></script>
	    <script src="{% static "js/bootstrap.min.js" %}"></script>
	    <script src="{% static "js/jquery-ui.js" %}"></script>
	    <script src="{% static "js/jquery.appendGrid-1.6.0.js" %}"></script>
	    <script src="{% static "js/jquery.plugin.js" %}"></script>
	    <script src="{% static "js/jquery.timeentry.js" %}"></script>
	    <script src="{% static "js/wickedpicker.js" %}"></script>
	    <script src="{% static "js/sb-admin-2.js" %}"></script>
	    <script src="{% static "js/metisMenu.min.js" %}"></script>
	    <script src="{% static "js/jquery.dataTables.min.js" %}"></script>
	    <script src="{% static "js/NumeroALetras.js" %}"></script>
	    <script src="{% static "js/spin.js" %}"></script>
	    <script src="{% static "js/validacionNumeros.js" %}"></script>
	    <script type="text/javascript">
		$.datepicker.regional['es'] = {
		closeText: 'Cerrar',
		prevText: '<Ant',
		nextText: 'Sig>',
		currentText: 'Hoy',
		monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
		monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
		dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
		dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sáb'],
		dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sá'],
		weekHeader: 'Sm',
		dateFormat: 'dd/mm/yy',
		firstDay: 1,
		isRTL: false,
		showMonthAfterYear: false,
		yearSuffix: ''
		};
		$.datepicker.setDefaults($.datepicker.regional['es']);
	    </script>
	</head>
	<body>
		<div id="wrapper">
			<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">	
				<div class="navbar-header">
			        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			            <span class="sr-only">Desplegar navegación</span>
			            <span class="icon-bar"></span>
			            <span class="icon-bar"></span>
			            <span class="icon-bar"></span>
			        </button>
			        <a class="navbar-brand" href="{% url 'seguridad:inicio' %}">
						<span class="glyphicon glyphicon-home"></span> Inicio
					</a>
					<a class="navbar-brand" href="{% url 'regional:tablero' %}">
						<span class="fa fa-line-chart fa-lg"></span> Proceso Regional	
					</a>
					<a class="navbar-brand" href="{% url 'nacional:tablero' %}">
						<span class="fa fa-line-chart fa-lg"></span> Proceso Nacional	
					</a>					
			    </div>
				<ul class="nav navbar-top-links navbar-right">
					<li class="dropdown">
					    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
					        <i class="fa fa-bell fa-fw"></i>  
					        <i class="fa fa-caret-down"></i>
					    </a>
					    <ul class="dropdown-menu dropdown-alerts">
					        <li>
					            <a href="#">
					                <div>
					                    <i class="fa fa-tasks fa-fw"></i> Nueva Alerta
					                    <span class="pull-right text-muted small">4 minutos antes</span>
					                </div>
					            </a>
					        </li>
					        <li class="divider"></li>		        
					        <li>
					            <a class="text-center" href="#">
					                <strong>Ver todas las alertas</strong>
					                <i class="fa fa-angle-right"></i>
					            </a>
					        </li>
					    </ul>		    
					</li>
					<li class="dropdown">
					    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
					        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
					    </a>
					    <ul class="dropdown-menu dropdown-user">
					        <li><a href="#"><i class="fa fa-user fa-fw"></i>Perfil de Usuario</a>
					        </li>
					        <li><a href="#"><i class="fa fa-gear fa-fw"></i>Ajustes</a>
					        </li>
					        <li class="divider"></li>
					        <li><a href="{% url 'seguridad:salir' %}"><i class="fa fa-sign-out fa-fw"></i>Salir</a>
					        </li>
					    </ul>		    
					</li>		
				</ul>
				{% block menu %}
		        {% endblock menu %}
		    </nav>
			<div id="page-wrapper">
				<div class="container-fluid">
	               	{% block cuerpo %}
	               	{% endblock cuerpo %}		
				</div>
			</div>					
			
		</div>
	</body>
	{% block js %}	
	{% endblock js %}
</html>

seguridad/templates/base_seguridad.html
{% extends "base.html" %}
{% block menu %}
<div class="navbar-default sidebar" role="navigation">
   	<div class="sidebar-nav navbar-collapse">
		<ul class="nav" id="side-menu">
			<li>
		        <a href="#"><i class="fa fa-user fa-lg"></i>Cuenta<span class="fa arrow"></span></a>
		        <ul class="nav nav-second-level">
		            <li><a href="{% url 'seguridad:cambiar_password' %}">Cambiar Contraseña</a></li>			   		 
		        </ul>	                
		    </li>
    	</ul>	               
	</div>                
</div>
{% endblock menu %}

seguridad/templates/bienvenida.html
{% extends "base_seguridad.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">VOLPOX - Voluntad Popular</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-info">
			<div class="panel-heading">
			    Bienvenido
			</div>
			<div class="panel-body">
				<div class='form-group'>
					<div class="row">
						<h3 class="text-center">Bienvenido al sistema, {{ user.first_name }} {{ user.last_name }}.</h3>						
					</div>
				</div>
			</div>
	</div>
</div>	
{% endblock cuerpo %}

seguridad/templates/cambiar_password.html
{% extends "base_seguridad.html" %}

{% block titulo_opcion %}
Cambio de Password
{% endblock titulo_opcion %} 

{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Cuenta</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    Cambiar Contraseña
			</div>
			<div class="panel-body">
				<form action="{% url 'seguridad:cambiar_password' %}" method="post" >
					{% csrf_token %}
					<div class="form-group">
						<label>Contraseña Actual:</label>
						{{ form.password_actual }}
						<p class="help-block">Ingrese su contraseña actual.</p>
					</div>
					<div class="form-group">
						<label>Contraseña Nueva:</label>
						{{ form.password_nueva }}
						<p class="help-block">Ingrese la contraseña nueva.</p>
					</div>
					<div class="form-group">
						<label>Contraseña de Verificación:</label>
						{{ form.password_verificacion }}
						<p class="help-block">Ingrese nuevamente la contraseña nueva.</p>
					</div>
					<button class="btn btn-medium btn-primary" type="submit"/>Cambiar Password</button>
				</form>		
			</div>
		</div>
	</div>
</div>
{% endblock cuerpo %}

seguridad/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
	    <meta charset="utf-8"/></meta>
	    <title>VOLPOX</title>
	    <meta content="width=device-width, initial-scale=1.0" name="viewport"></meta>
	    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}"></link>	 
	    <link href="{% static "css/sb-admin-2.css"  %}" rel="stylesheet" type="text/css" />    	    	    
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<div class="login-panel panel panel-default">
					    <div class="panel-heading">
					        <h3 class="panel-title">LOGIN</h3>
					    </div>
					    <div class="panel-body">
							<form role="form" method="post" id='form_login' action="{% url 'seguridad:login' %}">
								{% csrf_token %}
								<fieldset>
								    <div class="form-group">
								    	<label>Usuario:</label>
								        {{ form.usuario }}
								    </div>
								    <div class="form-group">
								    	<label>Contraseña:</label>
								        {{ form.password }}
								    </div>								    
								    <button class="btn btn-lg btn-success btn-block" type="submit" name="login"/>Login</button>
								</fieldset>
						    </form>
						</div>
			        </div>
			    </div>
			</div>
		</div>
	</body>
</html>