localizacion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from localizacion.views import Tablero, BusquedaProvincias, BusquedaDistritos,\
    seleccion_distrito, seleccion_prov_consejero, seleccion_provincia,\
    seleccion_region

urlpatterns = [
    url(r'^tablero/$',login_required(Tablero.as_view()), name="tablero"),
    url(r'^busquedaProvincias/$',login_required(BusquedaProvincias.as_view()), name="busquedaProvincias"),
    url(r'^busquedaDistritos/$',login_required(BusquedaDistritos.as_view()), name="busquedaDistritos"),
    url(r'^seleccion_distrito/$',login_required(seleccion_distrito), name="seleccion_distrito"),
    url(r'^seleccion_prov_consejero/$',login_required(seleccion_prov_consejero), name="seleccion_prov_consejero"),
    url(r'^seleccion_provincia/$',login_required(seleccion_provincia), name="seleccion_provincia"),
    url(r'^seleccion_region/$',login_required(seleccion_region), name="seleccion_region"),
]

regional/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from regional.views import ProcesarMesaMunicipal, ProcesarMesaRegional,\
    BusquedaMesas, ProcesarActaRegional, actas_municipales,\
    actas_regionales, mesas, detalle_acta_municipal, detalle_acta_regional,\
    exportar_actas_municipales, exportar_mesas, exportar_reporte_regional,\
    exportar_reporte_provincial, exportar_reporte_distrital,\
    reporte_presidente_regional, reporte_consejero_regional, reporte_provincial,\
    reporte_distrital, Tablero

urlpatterns = [
    url(r'^tablero/$',login_required(Tablero.as_view()), name="tablero"),
    url(r'^mesa_municipal/$',login_required(ProcesarMesaMunicipal.as_view()), name="mesa_municipal"),
    url(r'^mesa_regional/$',login_required(ProcesarMesaRegional.as_view()), name="mesa_regional"),
    url(r'^busquedaMesas/$',login_required(BusquedaMesas.as_view()), name="busquedaMesas"),
    #url(r'^acta_municipal/(?P<numero>\d+)/$',login_required(acta_municipal), name="acta_municipal"),
    url(r'^acta_regional/(?P<numero>\d+)/$',login_required(ProcesarActaRegional.as_view()), name="acta_regional"),
    url(r'^actas_municipales/$',login_required(actas_municipales), name="actas_municipales"),
    url(r'^actas_regionales/$',login_required(actas_regionales), name="actas_regionales"),
    url(r'^mesas/$',login_required(mesas), name="mesas"),
    url(r'^detalle_acta_municipal/(?P<acta>\d+)/$',login_required(detalle_acta_municipal), name="detalle_acta_municipal"),
    url(r'^detalle_acta_regional/(?P<acta>\d+)/$',login_required(detalle_acta_regional), name="detalle_acta_regional"),    
    url(r'^exportar_actas_municipales/$',login_required(exportar_actas_municipales), name="exportar_actas_municipales"),
    url(r'^exportar_mesas/$',login_required(exportar_mesas), name="exportar_mesas"),
    url(r'^exportar_reporte_regional/(?P<region>\d+)/$',login_required(exportar_reporte_regional), name="exportar_reporte_regional"),
    url(r'^exportar_reporte_provincial/(?P<provincia>\d+)/$',login_required(exportar_reporte_provincial), name="exportar_reporte_provincial"),
    url(r'^exportar_reporte_distrital/(?P<distrito>\d+)/$',login_required(exportar_reporte_distrital), name="exportar_reporte_distrital"),
    url(r'^reporte_presidente_regional/(?P<region>\d+)/$',login_required(reporte_presidente_regional), name="reporte_presidente_regional"),
    url(r'^reporte_consejero_regional/(?P<provincia>\d+)/$',login_required(reporte_consejero_regional), name="reporte_consejero_regional"),
    url(r'^reporte_provincial/(?P<provincia>\d+)/$',login_required(reporte_provincial), name="reporte_provincial"),
    url(r'^reporte_distrital/(?P<distrito>\d+)/$',login_required(reporte_distrital), name="reporte_distrital"),        
]

volpox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'volpox.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('seguridad.urls', namespace='seguridad')),
    url(r'^localizacion/', include('localizacion.urls', namespace='localizacion')),
    url(r'^regional/', include('regional.urls', namespace='regional')),
    url(r'^nacional/', include('nacional.urls', namespace='nacional')),
]

regional/forms.py
from django import forms

class FormularioMesa(forms.Form):
    mesas = forms.CharField(widget= forms.TextInput(attrs={'size': 100, 'class': 'form-control'}))  
    
class FormularioActaRegional(forms.Form):
    voto_blanco_pres = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control presidente','type': 'number'}))
    voto_nulo_pres = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control presidente','type': 'number'}))
    voto_impugnado_pres = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control presidente','type': 'number'}))
    voto_total_pres = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control presidente','type': 'number'}))
    voto_blanco_cons = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control consejero','type': 'number'}))
    voto_nulo_cons = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control consejero','type': 'number'}))
    voto_impugnado_cons = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control consejero','type': 'number'}))
    voto_total_cons = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control consejero','type': 'number'}))
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'cols': 146, 'rows': 5}))
    
class FormularioActaMunicipal(forms.Form):
    voto_blanco_prov = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control provincial','type': 'number'}))
    voto_nulo_prov = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control provincial','type': 'number'}))
    voto_impugnado_prov = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control provincial','type': 'number'}))
    voto_total_prov = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control provincial','type': 'number'}))
    voto_blanco_dis = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control distrital','type': 'number'}))
    voto_nulo_dis = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control distrital','type': 'number'}))
    voto_impugnado_dis = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control distrital','type': 'number'}))
    voto_total_dis = forms.CharField(widget= forms.TextInput(attrs={'size': 20, 'class': 'form-control distrital','type': 'number'}))
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'cols': 146, 'rows': 5}))

regional/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse
from regional.models import Mesa, DisenioActaRegional,\
    DetalleDisenioActaRegional, ActaRegional, DetalleActaRegional,\
    VotacionPresidenteRegional, VotacionConsejeroRegional, DisenioActaMunicipal,\
    DetalleDisenioActaMunicipal, ActaMunicipal, DetalleActaMunicipal,\
    VotacionProvincial, VotacionDistrital
from regional.forms import FormularioMesa, FormularioActaRegional,\
    FormularioActaMunicipal
from django.views.generic.base import TemplateView
from localizacion.models import CentroVotacion, Distrito, Provincia
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect
import csv
from django.db.models import Sum
# Create your views here.

class Tablero(TemplateView):
    template_name = "tablero_regional.html" 

class ProcesarMesaMunicipal(FormView):
    template_name = "mesa_municipal.html"
    form_class = FormularioMesa
    
    def get_context_data(self, **kwargs):
        mesas = Mesa.objects.filter(procesada_municipal=False)
        context = super(ProcesarMesaMunicipal, self).get_context_data(**kwargs)
        context['mesas'] = mesas
        return context
    
    def form_valid(self, form):
        data = form.cleaned_data
        mesa = data['mesas']
        try: 
            obj_mesa = Mesa.objects.get(pk=mesa)
            return HttpResponseRedirect(reverse('localizacion:acta_municipal', args=[mesa]))
        except Mesa.DoesNotExist:
            return HttpResponseRedirect(reverse('localizacion:mesa_municipal'))

class ProcesarMesaRegional(FormView):    
    template_name = "mesa_regional.html"
    form_class = FormularioMesa
    
    def get_context_data(self, **kwargs):
        mesas = Mesa.objects.filter(procesada_regional=False)
        context = super(ProcesarMesaRegional, self).get_context_data(**kwargs)
        context['mesas'] = mesas
        return context
    
    def form_valid(self, form):
        data = form.cleaned_data
        mesa = data['mesas']
        try: 
            obj_mesa = Mesa.objects.get(pk=mesa)
            return HttpResponseRedirect(reverse('localizacion:acta_regional', args=[mesa]))
        except Mesa.DoesNotExist:
            return HttpResponseRedirect(reverse('localizacion:mesa_regional'))   

class ProcesarActaRegional(FormView):
    template_name = "acta_regional.html"
    form_class = FormularioActaRegional
    
    def get(self, request, *args, **kwargs):
        self.numero = kwargs['numero']
        return super(ProcesarActaRegional, self).get(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        self.mesa = Mesa.objects.get(numero=self.numero)
        try:
            disenio_acta = DisenioActaRegional.objects.get(region=self.mesa.centro_votacion.distrito.provincia.region)
        except DisenioActaRegional.DoesNotExist:
            return HttpResponseRedirect(reverse('admin:login'))
        self.detalles = DetalleDisenioActaRegional.objects.filter(disenio_acta=disenio_acta).order_by('id')
        context = super(ProcesarActaRegional, self).get_context_data(**kwargs)
        context['mesa'] = self.mesa
        context['disenio_acta'] = disenio_acta
        context['detalles'] = self.detalles
        return context    
    
    def form_valid(self, form):
        data = form.cleaned_data
        votos_blancos_pres = data['voto_blanco_pres']
        votos_nulos_pres = data['voto_nulo_pres']
        votos_imp_pres = data['voto_impugnado_pres']
        votos_tot_pres = data['voto_total_pres']
        votos_blancos_cons = data['voto_blanco_cons']
        votos_nulos_cons = data['voto_nulo_cons']
        votos_imp_cons = data['voto_impugnado_cons']
        votos_tot_cons = data['voto_total_cons']
        acta = ActaRegional(mesa=self.mesa,votos_blancos_pres=votos_blancos_pres,votos_nulos_pres=votos_nulos_pres,
            votos_impugnados_pres=votos_imp_pres,votos_emitidos_pres=votos_tot_pres,votos_blancos_cons=votos_blancos_cons,
            votos_nulos_cons=votos_nulos_cons,votos_impugnados_cons=votos_imp_cons,votos_emitidos_cons=votos_tot_cons)
        acta.save()
        centro_votacion = self.mesa.centro_votacion
        distrito = centro_votacion.distrito
        provincia = distrito.provincia
        region = provincia.region
        for detalle in self.detalles:
            pres = "pres_"+str(detalle.partido.pk)
            votos_pres = self.request.POST[pres]
            cons = "cons_"+str(detalle.partido.pk)
            votos_cons = self.request.POST[cons]
            
            try:
                detalle_acta = DetalleActaRegional.objects.get(acta=acta,partido=detalle.partido)
            except DetalleActaRegional.DoesNotExist:
                detalle_acta = DetalleActaRegional(acta=acta,partido=detalle.partido)
                detalle_acta.votos_pres = 0
                detalle_acta.votos_cons = 0

            if not votos_pres.isnumeric():
                votos_pres=0
            else:
                try:
                    vot_pres = VotacionPresidenteRegional.objects.get(partido=detalle.partido, region=region)
                except VotacionPresidenteRegional.DoesNotExist:
                    vot_pres = VotacionPresidenteRegional(partido=detalle.partido, region=region)
                vot_pres.votos = vot_pres.votos + int(votos_pres) - detalle_acta.votos_pres
                vot_pres.save()
                
            if not votos_cons.isnumeric():
                votos_cons=0
            else:
                try:
                    vot_cons = VotacionConsejeroRegional.objects.get(partido=detalle.partido, provincia=provincia)
                except VotacionConsejeroRegional.DoesNotExist:
                    vot_cons = VotacionConsejeroRegional(partido=detalle.partido, provincia=provincia)
                vot_cons.votos = vot_cons.votos + int(votos_cons) - detalle_acta.votos_cons
                vot_cons.save()            
            
            detalle_acta.votos_pres=votos_pres
            detalle_acta.votos_cons=votos_cons
            detalle_acta.save()
        self.mesa.procesada_regional=True
        self.mesa.save()
        return HttpResponseRedirect(reverse('localizacion:mesa_regional')) 

def ProcesarActaMunicipal(FormView):
    template_name = "acta_municipal.html"
    form_class = FormularioActaMunicipal
    
    def get(self, request, *args, **kwargs):
        self.numero = kwargs['numero']
        return super(ProcesarActaMunicipal, self).get(request, *args, **kwargs)
    
    def get_initial(self):
        initial = super(ProcesarActaMunicipal, self).get_initial()
        initial['mesa'] = self.numero
        initial['votos_blancos'] = 0
        initial['votos_nulos'] = 0
        initial['votos_impugnados'] = 0
        initial['votos_totales'] = 0
        return initial 
    
    def get_context_data(self, **kwargs):
        context = super(ProcesarActaMunicipal, self).get_context_data(**kwargs)
        mesa = Mesa.objects.get(numero=self.numero)
        centro_votacion = mesa.centro_votacion
        distrito = centro_votacion.distrito
        provincia = distrito.provincia
        region = provincia.region
        try:
            disenio_acta = DisenioActaMunicipal.objects.get(distrito=distrito)
            context['disenio_acta'] = disenio_acta
            detalles = DetalleDisenioActaMunicipal.objects.filter(disenio_acta=disenio_acta).order_by('id')       
            context['mesa'] = mesa
            context['detalles'] = detalles
            return context           
        except DisenioActaMunicipal.DoesNotExist:
            return HttpResponseRedirect(reverse('regional:mesa_presidencial'))
    
    def post(self, request, *args, **kwargs):
        mesa = Mesa.objects.get(numero=request.POST['mesa'])
        votos_blancos_prov = request.POST['voto_blanco_prov']
        votos_nulos_prov = request.POST['voto_nulo_prov']
        votos_imp_prov = request.POST['voto_impugnado_prov']
        votos_tot_prov = request.POST['voto_total_provincial']
        centro_votacion = mesa.centro_votacion
        distrito = centro_votacion.distrito
        provincia = distrito.provincia
        region = provincia.region
        if not distrito.capital_provincia:
            votos_blancos_dis = request.POST['voto_blanco_dis']
            votos_nulos_dis = request.POST['voto_nulo_dis']
            votos_imp_dis = request.POST['voto_impugnado_dis']
            votos_tot_dis = request.POST['voto_total_distrital']
        else:
            votos_blancos_dis = 0
            votos_nulos_dis = 0
            votos_imp_dis = 0
            votos_tot_dis = 0
        disenio_acta = DisenioActaMunicipal.objects.get(distrito=distrito)
        detalles = DetalleDisenioActaMunicipal.objects.filter(disenio_acta=disenio_acta).order_by('id') 
        acta = ActaMunicipal(mesa=mesa,votos_blancos_prov=votos_blancos_prov,votos_blancos_dis=votos_blancos_dis,
            votos_nulos_prov=votos_nulos_prov,votos_nulos_dis=votos_nulos_dis,
            votos_impugnados_prov=votos_imp_prov,votos_impugnados_dis=votos_imp_dis,
            votos_emitidos_prov=votos_tot_prov,votos_emitidos_dis=votos_tot_dis)
        acta.save()
        for detalle in detalles:
            prov = "prov_"+str(detalle.partido.pk)
            votos_provincial = request.POST[prov]
            dis = "dis_"+str(detalle.partido.pk)
            votos_distrital = request.POST[dis]
            
            try:
                detalle_acta = DetalleActaMunicipal.objects.get(acta=acta,partido=detalle.partido)
            except DetalleActaMunicipal.DoesNotExist:
                detalle_acta = DetalleActaMunicipal(acta=acta,partido=detalle.partido)
                detalle_acta.votos_provincial = 0
                detalle_acta.votos_distrital = 0

regional/templates/acta_regional.html
{% extends "base_regional.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">ACTA ELECTORAL</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    MESA N°: {{ mesa.numero }}
			</div>
			<div class="panel-body">
				<form role="form" action="{% url 'actas:acta_regional' mesa.numero %}" method="post">								
					{% csrf_token %}
					<div class="form-group">
						<div class="row">
							<div class="col-md-6">
								CENTRO DE VOTACION: {{ mesa.centro_votacion }}
							</div>
							<div class="col-md-4">
								TOTAL DE ELECTORES: {{ mesa.total_electores }}
							</div>			
						</div>
						<div class="row">
							<div class="col-md-4">
								REGION: {{ region.nombre }}
							</div>
							<div class="col-md-4">
								PROVINCIA: {{ provincia.nombre }}
							</div>
							<div class="col-md-4">
								DISTRITO: {{ distrito.nombre }}
							</div>			
						</div>
					</div>
					<div class="row">
						<table class="table table-striped">
					        <thead>
					            <tr>
					                <th>PARTIDO</th>
					                <th>PRESIDENTE Y VICEPRESIDENTE</th>
					                <th>CONSEJERO</th>		                
					            </tr>
					        </thead>
					        <tbody>
								{% for detalle in detalles %}
									<tr>
						                <td>{{ detalle.partido }}</td>
						               	{% if detalle.presidente%}
						                	<td>
						                		<input type="number" name="pres_{{ detalle.partido.pk }}" id="pres_{{ detalle.partido.pk }}" min="0" max="{{ mesa.total_electores }}" value="0" class="presidente"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="pres_{{ detalle.partido.pk }}" id="pres_{{ detalle.partido.pk }}" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}
						                {% if detalle.consejero%}
						                	<td>
						                		<input type="number" name="cons_{{ detalle.partido.pk }}" id="cons_{{ detalle.partido.pk }}" min="0" max="{{ mesa.total_electores }}" value="0" class="consejero"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="cons_{{ detalle.partido.pk }}" id="cons_{{ detalle.partido.pk }}" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}			                		                
						            </tr>
								{% endfor %}
									<tr>
										<td>
											VOTOS EN BLANCO:
										</td>							
										<td>
											{{ form.voto_blanco_pres }}	
										</td>											
										<td>
											{{ form.voto_blanco_cons }}	
										</td>			   									
									</tr>
									<tr>
										<td>
											VOTOS NULOS:
										</td>
										<td>
											{{ form.voto_nulo_pres }}	
										</td>											
										<td>
											{{ form.voto_nulo_cons }}	
										</td>			                
									</tr>
									<tr>
										<td>
											VOTOS IMPUGNADOS:
										</td>
										<td>
											{{ form.voto_impugnado_pres }}	
										</td>											
										<td>
											{{ form.voto_impugnado_cons }}	
										</td>			                
									</tr>
									<tr>
										<td>
											TOTAL DE VOTOS EMITIDOS:
										</td>
										<td>
											{{ form.voto_total_pres }}	
										</td>											
										<td>
											{{ form.voto_total_cons }}	
										</td>			                
									</tr>								
							</tbody>
						</table>
					</div>
					<div class="row">
						<div class="col-lg-12">
						<label>OBSERVACIONES:</label>	
							{{ form.observaciones }}	
						</div>
					</div>
					<div class="row">
						<div class="col-lg-4">					
							<input class="btn btn-primary" type="submit" id="guardar" name="guardar" value="Guardar Acta">
						</div>
					</div>
					<div id="dialog" title="Error en el Total de Votos">
						<p>Error, el total de votos no puede ser mayor que el número de votantes</p>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock cuerpo %}

{% block js %}
	<script>
	
	$('.presidente').on('keyup',validarNumeros);
	$('.consejero').on('keyup',validarNumeros);

	function validarNumeros(){
		this.value = this.value.replace(/[^0-9]/g,'0');
	}	

	$('.presidente').on('change',totalPresidente);
	function totalPresidente(){
		var total_presidente = 0;
		$(".presidente").each(function(){
			total_presidente = total_presidente + eval($(this).val()); 
		});
		$("#id_voto_total_pres").val(total_presidente);
	}

	$('.consejero').on('change',totalConsejero);
	function totalConsejero(){
		var total_consejero = 0;
		$(".consejero").each(function(){
			total_consejero = total_consejero + eval($(this).val()); 
		});
		$("#id_voto_total_cons").val(total_consejero);
	}
	
	$("#dialog").dialog({
            autoOpen : false,
            resizable : false,
            width : 200,
            height:200,
            modal : true,
            buttons: {
                "Cerrar" : function(){
                    $( this ).dialog( "close" );
                }
            },
            close : function(ev, ui) {
                return true;    
            }
        });

	$('#guardar').on('mouseover',validarTotal);
	$('#guardar').on('focus',validarTotal);
	function validarTotal(){
		var total_presidente=eval($("#id_voto_total_pres").val());
		var total_consejero=eval($("#id_voto_total_cons").val());		
		var total_electores = {{ mesa.total_electores }};
		
		if(total_presidente>total_electores)
		{
			$( "#dialog" ).dialog("open");
		}
		else
		{
			if(total_consejero>total_electores)
			{
				$( "#dialog" ).dialog("open");
			}
			else
			{
			
			}
		}
	}

	</script>
{% endblock js %}

regional/templates/actas_municipales.html
{% extends "base_regional.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">MESA REGIONAL</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    SELECCIONE LA MESA
			</div>
			<div class="panel-body">
				<table class="table table-striped">
				    <thead>
				        <tr>
				            <th>MESA</th>
				            <th>V. VALIDOS PROV.</th>
				            <th>V. VALIDOS DIST.</th>
				            <th>V. BLANCOS PROV.</th>
				            <th>V. BLANCOS DIST.</th>
				            <th>V. NULOS PROV.</th>
				            <th>V. NULOS DIST.</th>
				            <th>V. IMPUG. PROV.</th>
				            <th>V. IMPUG. DIST.</th>
				            <th>TOTAL V. PROV.</th>
				            <th>TOTAL V. DIST.</th>
				            <th>VER</th>
				            <th>EDITAR</th>
				        </tr>
				    </thead>
				    <tbody>
				    {% for acta in actas %}
				        <tr>
				            <td>{{ acta.mesa }}</td>
				            <td>{{ acta.votos_validos_prov }}</td>
				            <td>{{ acta.votos_validos_dis }}</td>
				            <td>{{ acta.votos_blancos_prov }}</td>
				            <td>{{ acta.votos_blancos_dis }}</td>
				            <td>{{ acta.votos_nulos_prov }}</td>
				            <td>{{ acta.votos_nulos_dis }}</td>
				            <td>{{ acta.votos_impugnados_prov }}</td>
				            <td>{{ acta.votos_impugnados_dis }}</td>
				            <td>{{ acta.votos_emitidos_prov }}</td>
				            <td>{{ acta.votos_emitidos_dis }}</td>
				            <td>
				                <a class="btn btn-small" href="{% url 'regional:detalle_acta_municipal' acta.pk %}">
				                    <span class="glyphicon glyphicon-folder-open"></span>
				                </a>
				            </td>
				            <td>
				                <a class="btn btn-small" href="#">
				                    <span class="glyphicon glyphicon-pencil"></span>
				                </a>
				            </td>
				        </tr>        
				    {% endfor %}
				    </tbody>    
				</table>
				<a href="{% url 'regional:exportar_actas_municipales' %}">Exportar a Excel</a>
				<hr>
				<div>
				    <span>
				        {% if actas.has_previous %}
				            <a href="?pagina={{ actas.previous_page_number }}">Anterior</a>
				        {% endif %}
				            <span>
				            {{ actas.number }} de {{ actas.paginator.num_pages }}.
				            </span>
				        {% if actas.has_next %}
				            <a href="?pagina={{ actas.next_page_number }}">Siguiente</a>
				        {% endif %}
				    </span>
				</div>				
			</div>					
		</div>
	</div>
</div>

{% endblock cuerpo %}

regional/templates/base_regional.html
{% extends "base.html" %}
{% block menu %}
<div class="navbar-default sidebar" role="navigation">
   	<div class="sidebar-nav navbar-collapse">
		<ul class="nav" id="side-menu">
			<li>
		        <a href="#"><i class="fa fa-wrench fa-lg"></i> Configuración<span class="fa arrow"></span></a>
		        <ul class="nav nav-second-level">		            
		        </ul>	                
		    </li>			    
		    <li>
		        <a href="#"><i class="glyphicon glyphicon-sort"></i> Operaciones<span class="fa arrow"></span></a>
		        <ul class="nav nav-second-level">
					<li><a href="{% url 'regional:mesa_municipal' %}"> Actas Municipales</a></li>
		            <li><a href="{% url 'regional:mesa_regional' %}"> Actas Regionales</a></li>
				</ul>	                    
		    </li>
		    <li>
		    	<a href="#"><i class="glyphicon glyphicon-stats"></i> Reportes<span class="fa arrow"></span></a>
			    <ul class="nav nav-second-level">
			    	<li><a href="{% url 'regional:actas_municipales' %}"> Actas Municipales</a></li>
			    	<li><a href="{% url 'regional:actas_regionales' %}"> Actas Regionales</a></li>
			    	<li><a href="{% url 'localizacion:seleccion_region' %}"> Presidente Regional</a></li>
					<li><a href="{% url 'localizacion:seleccion_prov_consejero' %}"> Consejero Regional</a></li>
					<li><a href="{% url 'localizacion:seleccion_provincia' %}"> Municipalidad Provincial</a></li>
					<li><a href="{% url 'localizacion:seleccion_distrito' %}"> Municipalidad Distrital</a></li>
				</ul>
		    </li>
    	</ul>	               
	</div>                
</div>

{% endblock menu %}