localizacion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from localizacion.views import Tablero, BusquedaProvincias, BusquedaDistritos,\
    seleccion_distrito, seleccion_prov_consejero, seleccion_provincia,\
    seleccion_region

urlpatterns = [
    url(r'^tablero/$',login_required(Tablero.as_view()), name="tablero"),
    url(r'^busquedaProvincias/$',login_required(BusquedaProvincias.as_view()), name="busquedaProvincias"),
    url(r'^busquedaDistritos/$',login_required(BusquedaDistritos.as_view()), name="busquedaDistritos"),
    url(r'^seleccion_distrito/$',login_required(seleccion_distrito), name="seleccion_distrito"),
    url(r'^seleccion_prov_consejero/$',login_required(seleccion_prov_consejero), name="seleccion_prov_consejero"),
    url(r'^seleccion_provincia/$',login_required(seleccion_provincia), name="seleccion_provincia"),
    url(r'^seleccion_region/$',login_required(seleccion_region), name="seleccion_region"),
]

nacional/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from nacional.views import MesaPresidencial, Tablero, ProcesarActaPresidencial, \
    ReportePresidente, ActasPresidenciales, MesasNacionales, MesaCongresal, \
    ProcesarActaCongresal, ActasCongresales, ReporteCongresal

urlpatterns = [
    url(r'^tablero/$', login_required(Tablero.as_view()), name="tablero"),
    url(r'^mesa_presidencial/$', login_required(MesaPresidencial.as_view()), name="mesa_presidencial"),
    url(r'^mesa_congresal/$', login_required(MesaCongresal.as_view()), name="mesa_congresal"),
    url(r'^reporte_presidente/$', login_required(ReportePresidente.as_view()), name="reporte_presidente"),
    url(r'^acta_presidencial/(?P<numero>\d+)/$', login_required(ProcesarActaPresidencial.as_view()),
        name="acta_presidencial"),
    url(r'^acta_congresal/(?P<numero>\d+)/$', login_required(ProcesarActaCongresal.as_view()), name="acta_congresal"),
    url(r'^actas_presidenciales/$', login_required(ActasPresidenciales.as_view()), name="actas_presidenciales"),
    url(r'^actas_congresales/$', login_required(ActasCongresales.as_view()), name="actas_congresales"),
    url(r'^mesas_nacionales/$', login_required(MesasNacionales.as_view()), name="mesas_nacionales"),
    url(r'^reporte_congresal/(?P<region>\d+)/$', login_required(ReporteCongresal.as_view()), name="reporte_congresal"),
]

volpox/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'volpox.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('seguridad.urls', namespace='seguridad')),
    url(r'^localizacion/', include('localizacion.urls', namespace='localizacion')),
    url(r'^regional/', include('regional.urls', namespace='regional')),
    url(r'^nacional/', include('nacional.urls', namespace='nacional')),
]

nacional/forms.py
from django import forms


class FormularioMesaNacional(forms.Form):
    mesas = forms.CharField(widget=forms.TextInput(attrs={'size': 100, 'class': 'form-control'}))


class FormularioActaPresidencial(forms.Form):
    mesa = forms.CharField(widget=forms.HiddenInput())
    votos_blancos = forms.CharField(widget=forms.TextInput(
        attrs={'size': 20, 'class': 'form-control numerico presidente', 'type': 'number', 'min': '0'}))
    votos_nulos = forms.CharField(widget=forms.TextInput(
        attrs={'size': 20, 'class': 'form-control numerico presidente', 'type': 'number', 'min': '0'}))
    votos_impugnados = forms.CharField(widget=forms.TextInput(
        attrs={'size': 20, 'class': 'form-control numerico presidente', 'type': 'number', 'min': '0'}))
    votos_totales = forms.CharField(widget=forms.TextInput(
        attrs={'size': 20, 'class': 'form-control numerico total', 'type': 'number', 'min': '0',
               'readonly': 'readonly'}))
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'cols': 141, 'rows': 5}))


class FormularioActaCongresal(forms.Form):
    mesa = forms.CharField(widget=forms.HiddenInput())
    votos_blancos = forms.CharField(
        widget=forms.TextInput(attrs={'size': 20, 'class': 'form-control congresal', 'type': 'number', 'min': '0'}))
    votos_nulos = forms.CharField(
        widget=forms.TextInput(attrs={'size': 20, 'class': 'form-control congresal', 'type': 'number', 'min': '0'}))
    votos_impugnados = forms.CharField(
        widget=forms.TextInput(attrs={'size': 20, 'class': 'form-control congresal', 'type': 'number', 'min': '0'}))
    votos_totales = forms.CharField(widget=forms.TextInput(
        attrs={'size': 20, 'class': 'form-control numerico', 'type': 'number', 'min': '0', 'readonly': 'readonly'}))
    observaciones = forms.CharField(widget=forms.Textarea(attrs={'cols': 108, 'rows': 5}))

nacional/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from nacional.forms import FormularioMesaNacional, FormularioActaPresidencial,\
    FormularioActaCongresal
from nacional.models import MesaNacional, DisenioActaPresidencial,\
    DetalleDisenioActaPresidencial, ActaPresidencial, DetalleActaPresidencial,\
    VotacionPresidente, DisenioActaCongresal, DetalleDisenioActaCongresal,\
    ActaCongresal, DetalleActaCongresal, VotacionCongresalCandidato
from django.http.response import HttpResponseRedirect
from django.core.urlresolvers import reverse
from localizacion.models import CentroVotacion, Provincia, Distrito, Partido
from django.db.models import Sum
from django.views.generic.list import ListView

# Create your views here.
class Tablero(TemplateView):
    template_name = "tablero_nacional.html"        

class MesaPresidencial(FormView):
    template_name = "mesa_presidencial.html"
    form_class = FormularioMesaNacional
    
    def get_context_data(self, **kwargs):
        mesas = MesaNacional.objects.filter(procesada_presidencial=False)
        context = super(MesaPresidencial, self).get_context_data(**kwargs)
        context['mesas'] = mesas
        return context
    
    def form_valid(self, form):
        data = form.cleaned_data
        mesa = data['mesas']
        try: 
            obj_mesa = MesaNacional.objects.get(pk=mesa)
            return HttpResponseRedirect(reverse('nacional:acta_presidencial', args=[mesa]))
        except MesaNacional.DoesNotExist:
            return HttpResponseRedirect(reverse('nacional:mesa_presidencial'))
        
class ProcesarActaPresidencial(FormView):
    template_name = "acta_presidencial.html"
    form_class = FormularioActaPresidencial
    
    def get(self, request, *args, **kwargs):
        self.numero = kwargs['numero']
        return super(ProcesarActaPresidencial, self).get(request, *args, **kwargs)
    
    def get_initial(self):
        initial = super(ProcesarActaPresidencial, self).get_initial()
        initial['mesa'] = self.numero
        initial['votos_blancos'] = 0
        initial['votos_nulos'] = 0
        initial['votos_impugnados'] = 0
        initial['votos_totales'] = 0
        return initial 
    
    def get_context_data(self, **kwargs):
        context = super(ProcesarActaPresidencial, self).get_context_data(**kwargs)
        mesa = MesaNacional.objects.get(numero=self.numero)
        try:
            disenio_acta = DisenioActaPresidencial.objects.get(pk=1) 
            context['disenio_acta'] = disenio_acta
            detalles = DetalleDisenioActaPresidencial.objects.filter(disenio_acta=disenio_acta).order_by('id')        
            context['mesa'] = mesa
            context['detalles'] = detalles
            return context           
        except DisenioActaPresidencial.DoesNotExist:
            return HttpResponseRedirect(reverse('nacional:mesa_presidencial'))            
    
    def post(self, request, *args, **kwargs):
        mesa = MesaNacional.objects.get(numero=request.POST['mesa'])
        votos_blancos = request.POST['votos_blancos']
        votos_nulos = request.POST['votos_nulos']
        votos_imp = request.POST['votos_impugnados']
        votos_tot = request.POST['votos_totales']
        acta = ActaPresidencial(mesa=mesa,votos_blancos=votos_blancos,votos_nulos=votos_nulos,votos_impugnados=votos_imp,votos_emitidos=votos_tot)
        acta.save()
        centro_votacion = mesa.centro_votacion
        distrito = centro_votacion.distrito
        provincia = distrito.provincia
        region = provincia.region
        disenio_acta = DisenioActaPresidencial.objects.get(pk=1)
        detalles = DetalleDisenioActaPresidencial.objects.filter(disenio_acta=disenio_acta).order_by('id')
        for detalle in detalles:
            pres = "pres_"+str(detalle.partido.pk)
            votos_pres = self.request.POST[pres]
            try:
                detalle_acta = DetalleActaPresidencial.objects.get(acta=acta,partido=detalle.partido)
            except DetalleActaPresidencial.DoesNotExist:
                detalle_acta = DetalleActaPresidencial(acta=acta,partido=detalle.partido)              
                detalle_acta.votos = 0
            if not votos_pres.isnumeric():
                votos_pres=0
            else:
                try:
                    vot_pres = VotacionPresidente.objects.get(partido=detalle.partido)
                except VotacionPresidente.DoesNotExist:
                    vot_pres = VotacionPresidente(partido=detalle.partido)
                vot_pres.votos = vot_pres.votos + int(votos_pres) - detalle_acta.votos
                vot_pres.save()                
            detalle_acta.votos=votos_pres
            detalle_acta.save()
        mesa.procesada_presidencial=True
        mesa.save()
        return HttpResponseRedirect(reverse('nacional:mesa_presidencial'))
    
class MesaCongresal(FormView):
    template_name = "mesa_congresal.html"
    form_class = FormularioMesaNacional
    
    def get_context_data(self, **kwargs):
        mesas = MesaNacional.objects.filter(procesada_congresal=False)
        context = super(MesaCongresal, self).get_context_data(**kwargs)
        context['mesas'] = mesas
        return context
    
    def form_valid(self, form):
        data = form.cleaned_data
        mesa = data['mesas']
        try: 
            obj_mesa = MesaNacional.objects.get(pk=mesa)
            return HttpResponseRedirect(reverse('nacional:acta_congresal', args=[mesa]))
        except MesaNacional.DoesNotExist:
            return HttpResponseRedirect(reverse('nacional:mesa_congresal'))
        
class ProcesarActaCongresal(FormView):
    template_name = "acta_congresal.html"
    form_class = FormularioActaCongresal
    
    def get(self, request, *args, **kwargs):
        self.numero = kwargs['numero']
        return super(ProcesarActaCongresal, self).get(request, *args, **kwargs)
    
    def get_initial(self):
        initial = super(ProcesarActaCongresal, self).get_initial()
        initial['mesa'] = self.numero
        initial['votos_blancos'] = 0
        initial['votos_nulos'] = 0
        initial['votos_impugnados'] = 0
        initial['votos_totales'] = 0
        return initial 
    
    def get_context_data(self, **kwargs):
        context = super(ProcesarActaCongresal, self).get_context_data(**kwargs)
        mesa = MesaNacional.objects.get(numero=self.numero)
        try:
            disenio_acta = DisenioActaCongresal.objects.get(region=mesa.centro_votacion.distrito.provincia.region) 
            context['disenio_acta'] = disenio_acta
            detalles = DetalleDisenioActaCongresal.objects.filter(disenio_acta=disenio_acta).order_by('id')        
            context['mesa'] = mesa
            context['detalles'] = detalles
            return context           
        except DisenioActaCongresal.DoesNotExist:
            return HttpResponseRedirect(reverse('nacional:mesa_congresal'))            
    
    def post(self, request, *args, **kwargs):
        mesa = MesaNacional.objects.get(numero=request.POST['mesa'])
        votos_blancos = request.POST['votos_blancos']
        votos_nulos = request.POST['votos_nulos']
        votos_imp = request.POST['votos_impugnados']
        votos_tot = request.POST['votos_totales']
        acta = ActaCongresal(mesa=mesa,votos_blancos=votos_blancos,votos_nulos=votos_nulos,votos_impugnados=votos_imp,votos_emitidos=votos_tot)
        acta.save()
        centro_votacion = mesa.centro_votacion
        distrito = centro_votacion.distrito
        provincia = distrito.provincia
        region = provincia.region
        disenio_acta = DisenioActaCongresal.objects.get(region=mesa.centro_votacion.distrito.provincia.region)
        detalles = DetalleDisenioActaCongresal.objects.filter(disenio_acta=disenio_acta).order_by('id')
        for detalle in detalles:
            cong_total = "total_"+str(detalle.partido.pk)
            votos_cong_total = self.request.POST[cong_total]
            if not votos_cong_total.isnumeric():
                votos_cong_total=0
            else:
                try:
                    vot_cong_tot = VotacionCongresalCandidato.objects.get(partido=detalle.partido,region=region)
                except VotacionCongresalCandidato.DoesNotExist:
                    vot_cong_tot = VotacionCongresalCandidato(partido=detalle.partido,region=region)
                vot_cong_tot.votos += int(votos_cong_total)
                vot_cong_tot.save()
            for i in range(1,8):
                cong = "cong_"+str(detalle.partido.pk)+"_"+str(i)
                votos_cong = self.request.POST[cong]
                try:
                    detalle_acta = DetalleActaCongresal.objects.get(acta=acta,partido=detalle.partido,numero=i)
                except DetalleActaCongresal.DoesNotExist:
                    detalle_acta = DetalleActaCongresal(acta=acta,partido=detalle.partido,numero=i)              
                    detalle_acta.votos = 0
                if not votos_cong.isnumeric():
                    votos_cong=0
                else:
                    try:
                        vot_cong = VotacionCongresalCandidato.objects.get(partido=detalle.partido,region=region,numero=i)
                    except VotacionCongresalCandidato.DoesNotExist:
                        vot_cong = VotacionCongresalCandidato(partido=detalle.partido,region=region,numero=i)
                    vot_cong.votos = vot_cong.votos + int(votos_cong) - detalle_acta.votos
                    vot_cong.save()                
                detalle_acta.votos = votos_cong
                detalle_acta.save()
        mesa.procesada_congresal=True
        mesa.save()
        return HttpResponseRedirect(reverse('nacional:mesa_congresal'))
    
class ReportePresidente(TemplateView):
    template_name = "reporte_presidente.html"
    
    def get_context_data(self, **kwargs):

nacional/templates/acta_congresal.html
{% extends "base_nacional.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">ACTA ELECTORAL CONGRESAL</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				MESA N°: {{ mesa.numero }}
			</div>
			<div class="panel-body">
				<form role="form" action="{% url 'nacional:acta_congresal' mesa.numero %}" method="post">								
					{% csrf_token %}
					<div class="form-group">
						<div class="row">
							<div class="col-md-6">
								{{ form.mesa }}
								CENTRO DE VOTACION: {{ mesa.centro_votacion }}
							</div>
							<div class="col-md-4">
								TOTAL DE ELECTORES: {{ mesa.total_electores }}
							</div>			
						</div>
						<div class="row">
							<div class="col-md-4">
								REGION: {{ mesa.centro_votacion.distrito.provincia.region.nombre }}
							</div>
							<div class="col-md-4">
								PROVINCIA: {{ mesa.centro_votacion.distrito.provincia.nombre }}
							</div>
							<div class="col-md-4">
								DISTRITO: {{ mesa.centro_votacion.distrito.nombre }}
							</div>			
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
						<table class="table table-striped">
					        <thead>
					            <tr>
					                <th>PARTIDO</th>
					                <th>TOTAL</th>
					                <th>1</th>
					                <th>2</th>
					                <th>3</th>
					                <th>4</th>
					                <th>5</th>
					                <th>6</th>
					                <th>7</th>					                		                
					            </tr>
					        </thead>
					        <tbody>
								{% for detalle in detalles %}
									<tr>
						                <td>{{ detalle.partido }}</td>
						                <td width="10">
						                	<input type="number" style="width: 5em" name="total_{{ detalle.partido.pk }}" id="total_{{ detalle.partido.pk }}" min="0" max="{{ mesa.total_electores }}" value="0" class="congresal" readonly/></td>
						               	{% if detalle.numero1%}
						                	<td width="50">
						                		<input type="number" style="width: 4em" name="cong_{{ detalle.partido.pk }}_1" id="cong_{{ detalle.partido.pk }}_1" min="0" max="{{ mesa.total_electores }}" value="0" class="{{ detalle.partido.pk }}"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="cong_{{ detalle.partido.pk }}_1" id="cong_{{ detalle.partido.pk }}_1" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}
						                {% if detalle.numero2%}
						                	<td>
						                		<input type="number" style="width: 4em" name="cong_{{ detalle.partido.pk }}_2" id="cong_{{ detalle.partido.pk }}_2" min="0" max="{{ mesa.total_electores }}" value="0" class="{{ detalle.partido.pk }}"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="cong_{{ detalle.partido.pk }}_2" id="cong_{{ detalle.partido.pk }}_2" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}
						                {% if detalle.numero3 %}
						                	<td>
						                		<input type="number" style="width: 4em" name="cong_{{ detalle.partido.pk }}_3" id="cong_{{ detalle.partido.pk }}_3" min="0" max="{{ mesa.total_electores }}" value="0" class="{{ detalle.partido.pk }}"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="cong_{{ detalle.partido.pk }}_3" id="cong_{{ detalle.partido.pk }}_3" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}
						                {% if detalle.numero4 %}
						                	<td>
						                		<input type="number" style="width: 4em" name="cong_{{ detalle.partido.pk }}_4" id="cong_{{ detalle.partido.pk }}_4" min="0" max="{{ mesa.total_electores }}" value="0" class="{{ detalle.partido.pk }}"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="cong_{{ detalle.partido.pk }}_4" id="cong_{{ detalle.partido.pk }}_4" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}
						                {% if detalle.numero5 %}
						                	<td>
						                		<input type="number" style="width: 4em" name="cong_{{ detalle.partido.pk }}_5" id="cong_{{ detalle.partido.pk }}_5" min="0" max="{{ mesa.total_electores }}" value="0" class="{{ detalle.partido.pk }}"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="cong_{{ detalle.partido.pk }}_5" id="cong_{{ detalle.partido.pk }}_5" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}
						                {% if detalle.numero6 %}
						                	<td>
						                		<input type="number" style="width: 4em" name="cong_{{ detalle.partido.pk }}_6" id="cong_{{ detalle.partido.pk }}_6" min="0" max="{{ mesa.total_electores }}" value="0" class="{{ detalle.partido.pk }}"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="cong_{{ detalle.partido.pk }}_6" id="cong_{{ detalle.partido.pk }}_6" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}
						                {% if detalle.numero7 %}
						                	<td>
						                		<input type="number" style="width: 4em" name="cong_{{ detalle.partido.pk }}_7" id="cong_{{ detalle.partido.pk }}_7" min="0" max="{{ mesa.total_electores }}" value="0" class="{{ detalle.partido.pk }}"/>
						                	</td>
						                {% else %}
						                	<td>
						                		<input type="text" name="cong_{{ detalle.partido.pk }}_7" id="cong_{{ detalle.partido.pk }}_7" value="NO TIENE LISTA" readonly/>
						                	</td>
						                {% endif %}
						            </tr>
								{% endfor %}
									<tr>
										<td>
											VOTOS EN BLANCO:
										</td>							
										<td>
											{{ form.votos_blancos }}	
										</td>		   									
									</tr>
									<tr>
										<td>
											VOTOS NULOS:
										</td>
										<td>
											{{ form.votos_nulos }}	
										</td>		                
									</tr>
									<tr>
										<td>
											VOTOS IMPUGNADOS:
										</td>
										<td>
											{{ form.votos_impugnados }}	
										</td>		                
									</tr>
									<tr>
										<td>
											TOTAL DE VOTOS EMITIDOS:
										</td>
										<td>
											{{ form.votos_totales }}	
										</td>		                
									</tr>								
							</tbody>
						</table>
						</div>
					</div>
					<div class="row">
						<div class="col-lg-12">
						<label>OBSERVACIONES:</label>	
							{{ form.observaciones }}	
						</div>
					</div>
					<div class="row">
						<div class="col-lg-4">					
							<input class="btn btn-primary" type="submit" id="guardar" name="guardar" value="Guardar Acta">
						</div>
					</div>
					<div id="dialog" title="Error en el Total de Votos">
						<p>Error, el total de votos no puede ser mayor que el número de votantes</p>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock cuerpo %}

{% block js %}
<script>
	
	$(".congresal").keydown(validar_numeros);
	$('.1').keydown(validar_numeros);
	$('.2').keydown(validar_numeros);
	$('.3').keydown(validar_numeros);
	$('.4').keydown(validar_numeros);
	$('.5').keydown(validar_numeros);
	$('.6').keydown(validar_numeros);
	$('.7').keydown(validar_numeros);
	$('.1').on('change',totalCongreso);
	$('.2').on('change',totalCongreso);
	$('.3').on('change',totalCongreso);
	$('.4').on('change',totalCongreso);
	$('.5').on('change',totalCongreso);
	$('.6').on('change',totalCongreso);
	$('.7').on('change',totalCongreso);
	$(".congresal").on('change',total);
	
	function totalCongreso()
	{
		var total_congreso = 0;
		$("."+$(this).attr("class")).each(function()
		{
			total_congreso = total_congreso + eval($(this).val()); 
		});
		
		$("#total_"+$(this).attr("class")).val(total_congreso);
		total();
	}	
	
	function total()
	{
		var total = 0;
		
		$(".congresal").each(function()
		{
			total = total + eval($(this).val()); 
		});
		
		$("#id_votos_totales").val(total);
	}
	
	$("#dialog").dialog({
            autoOpen : false,
            resizable : false,
            width : 200,
            height:200,
            modal : true,
            buttons: {
                "Cerrar" : function(){
                    $( this ).dialog( "close" );
                }
            },
            close : function(ev, ui) {
                return true;    
            }
        });

	$("form").submit(function(event) 
	{
		var total_congreso=eval($("#id_votos_totales").val());
		var total_electores = {{ mesa.total_electores }};
		if(total_congreso>total_electores)
		{
			$( "#dialog" ).dialog("open");
		}
		else
		{
			return;
		}
		event.preventDefault();
	});

	</script>
{% endblock js %}

nacional/templates/base_nacional.html
{% extends "base.html" %}
{% block menu %}
<div class="navbar-default sidebar" role="navigation">
   	<div class="sidebar-nav navbar-collapse">
		<ul class="nav" id="side-menu">
			<li>
		        <a href="#"><i class="fa fa-wrench fa-lg"></i> Configuración<span class="fa arrow"></span></a>
		        <ul class="nav nav-second-level">
		            
		        </ul>	                
		    </li>			    
		    <li>
		        <a href="#"><i class="glyphicon glyphicon-sort"></i> Operaciones<span class="fa arrow"></span></a>
		        <ul class="nav nav-second-level">
					<li><a href="{% url 'nacional:mesa_presidencial' %}">Acta Presidencial</a></li>
					<li><a href="{% url 'nacional:mesa_congresal' %}">Acta Congresal</a></li>		            
				</ul>	                    
		    </li>
		    <li>
		    	<a href="#"><i class="glyphicon glyphicon-stats"></i> Reportes<span class="fa arrow"></span></a>
			    <ul class="nav nav-second-level">
			    	<li><a href="{% url 'nacional:reporte_presidente' %}">Resultados Presidenciales</a></li>
			    	<li><a href="{% url 'localizacion:seleccion_region' %}">Resultados Congresales</a></li>
			    	<li><a href="{% url 'nacional:actas_presidenciales' %}">Actas Presidenciales</a></li>
			    	<li><a href="{% url 'nacional:actas_congresales' %}">Actas Congresales</a></li>
			    	<li><a href="{% url 'nacional:mesas_nacionales' %}">Mesas</a></li>
				</ul>
		    </li>
    	</ul>	               
	</div>                
</div>

{% endblock menu %}

nacional/templates/mesa_congresal.html
{% extends "base_nacional.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">MESA NACIONAL</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    SELECCIONE LA MESA
			</div>
			<div class="panel-body">
				<form role="form" action="#" method="post">			
					{% csrf_token %}
					<div class="form-group">
						<label>Mesa:</label>
						{{ form.mesas }}
						<p class="help-block">Digite la mesa a procesar.</p>
					</div>					
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock cuerpo %}

{% block js %}
<script>
	var mesas = []
	{% for mesa in mesas %}
	mesas.push("{{ mesa.numero }}")
	{% endfor %}
	$(function() {
		$("#id_mesas").autocomplete({source: mesas});
	});
</script>
{% endblock js %}

nacional/templates/mesa_presidencial.html
{% extends "base_nacional.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">MESA NACIONAL</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    SELECCIONE LA MESA
			</div>
			<div class="panel-body">
				<form role="form" action="{% url 'nacional:mesa_presidencial' %}" method="post">			
					{% csrf_token %}
					<div class="form-group">
						<label>Mesa:</label>
						{{ form.mesas }}
						<p class="help-block">Digite la mesa a procesar.</p>
					</div>					
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock cuerpo %}

{% block js %}
<script>
	var mesas = []
	{% for mesa in mesas %}
	mesas.push("{{ mesa.numero }}")
	{% endfor %}
	$(function() {
		$("#id_mesas").autocomplete({source: mesas});
	});
</script>
{% endblock js %}

nacional/templates/tablero_nacional.html
{% extends "base_nacional.html" %}
{% block cuerpo %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tablero</h1>
    </div>    
</div>
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
			    <i class="fa fa-bell fa-fw"></i>Panel de Notificaciones.
			</div>
			<div class="panel-body">
				<div class="list-group">
					{% for notificacion in notificaciones %}
						<p class="list-group-item">{{ notificacion }}</p>
					{% endfor %}
				</div>			
			</div>
		</div>
	</div>
</div>
{% endblock cuerpo %}

{% block js %}
<script language="javascript" type="text/javascript">
</script>
{% endblock js %}